# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-24 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neural_sessions', '0008_auto_20171218_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralsession',
            name='bsession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='runner.Session'),
        ),
        migrations.AlterField(
            model_name='neuralsession',
            name='grand_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='runner.GrandSession'),
        ),
    ]
