# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-24 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0029_auto_20190312_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='cage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='runner.BehaviorCage'),
        ),
        migrations.AlterField(
            model_name='optosession',
            name='behavioral_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='runner.Session'),
        ),
        migrations.AlterField(
            model_name='optosession',
            name='grand_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='runner.GrandSession'),
        ),
        migrations.AlterField(
            model_name='session',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='runner.Board'),
        ),
        migrations.AlterField(
            model_name='session',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='runner.Box'),
        ),
        migrations.AlterField(
            model_name='session',
            name='grand_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='runner.GrandSession'),
        ),
        migrations.AlterField(
            model_name='session',
            name='mouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='runner.Mouse'),
        ),
    ]
