# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-07-05 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisk_video', '0013_videosession_param_colorize_length_thresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='param_edge_crop_x0',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='param_edge_crop_x1',
            field=models.IntegerField(blank=True, default=640, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='param_edge_crop_y0',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='param_edge_crop_y1',
            field=models.IntegerField(blank=True, default=550, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='param_edge_lumthresh',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='param_edge_split_iters',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='param_edge_x0',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='param_edge_x1',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='param_edge_y1',
            field=models.IntegerField(blank=True, default=550, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='param_face_side',
            field=models.IntegerField(blank=True, choices=[(0, 'left'), (1, 'right'), (2, 'top'), (3, 'bottom')], default=1, null=True),
        ),
    ]
